apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: demoapp
  name: demoapp-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: demoapp
    spec:
      containers:
      - image: chittaranjanpanda/demoapp
        name: demoapp
        ports:
        - name: demoapp
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demoapp
  name: demoapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 10080
  selector:
    name: demoapp
