apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: chittaranjanpanda/demoapp:latest
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
spec:
  selector:
    app: demoapp

  ports:
    - name: http
      port: 8080
      nodePort: 30080

  type: NodePort
